spring.application.name=employee-management

# Database Configuration for Docker file changed for localhost to host.docker.internal to connect to the database running on the host machine from within the Docker container
# becuse the Docker container has its own network and cannot access the host machine's localhost directly. Using host.docker.internal allows the container to communicate with services running on the host machine.
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/employee_management
spring.datasource.username=root
spring.datasource.password=Sunflower@sa05!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081